name: "JFrog NPM Integration Tetris_Game"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
permissions:
  actions: read # for detecting the Github actions environment.
  id-token: write # for creating OIDC tokens for signing
  packages: write # for uploading attestions
  contents: read 

jobs:
  sonar:
    name: code quality analysis
    runs-on: ubuntu-latest #[Linux] 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
         args: >
          -Dsonar.projectBaseDir=src
          -Dsonar.projectKey=Tetris_Game
          -Dsonar.projectName=Tetris_Game
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**,**/disk/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      
      # If you wish to fail your job when the Quality Gate is red,  This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
           node-version: '16'
          
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      # - name: Trivy file scan
      #   run: trivy fs . > trivyfs.txt

  publish-build:
  permissions:
    id-token: write
    runs-on: ubuntu-latest #[Linux]
    needs: [sonar]
    env:
       JF_URL: ${{ vars.JF_URL }}
       LOCAL_REPO: tetris-game
       VIRTUAL_REPO: virtual-tetris-game
       
    steps:

      - name: Checkout
        uses: actions/checkout@v3
         
      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          chmod +x jfrog
          sudo mv jfrog /usr/local/bin/

      - name: Setup JFrog CLI OIDC
        uses:  jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:  
          JF_URL: ${{ vars.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          oidc-provider-name: github-jfrog
          oidc-audience: my-aud
           
      - name: Setup Node npm
        uses: actions/setup-node@v4

      - uses: jfrog/setup-jfrog-cli@v4
        id: jf-cli
        with:
          version: latest
          oidc: true
           
      - name: Set CLI Config
        run: | #jf npm-config --global=true --repo-resolve=arctiq-npm --repo-deploy=arctiq-npm
          jf config add my-server --url=$JF_URL --interactive=false --oidc-token-id="${{ steps.jf-cli.outputs.oidc-token }}"
          jf npm-config --repo-resolve=$VIRTUAL_REPO --repo-deploy=$LOCAL_REPO --server-id-resolve=my-server --server-id-deploy=my-server           
       
      - name: Install Deps
        run: jf npm install
           
       #- name: Run tests
         #run: npm test
         
      - name: Publish
        run: jf npm publish
         
      - name: Publish Build info With JFrog CLI
        run: |
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish

  # docker-push:
  #   runs-on: [Linux]
  #   needs: [sonar, publish-build]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup JFrog CLI with OIDC
  #       uses: jfrog/setup-jfrog-cli@v4
  #       id: setup-cli
  #       env:
  #         JF_URL: ${{ vars.JF_URL }}
  #         JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         oidc-provider-name: github-jfrog
  #         oidc-audience: my-aud
        
  #     - name: Build Docker image
  #       run: |
  #         IMAGE_TAG=${{ github.sha }}
  #         docker build -t ${{ secrets.JF_URL }}/${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}:$IMAGE_TAG .

  #     - name: Push Docker image
  #       run: |
  #         docker push ${{ secrets.JF_URL }}/${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.sha }}
  
  # Image-scan:
  #   runs-on: [Linux]
  #   needs: [docker-push]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Log in to JFrog
  #       run: |
  #         echo "${{ secrets.JFROG_TOKEN }}" | docker login ${{ secrets.JFROG_URL }} --username ${{ secrets.JFROG_USERNAME }} --password-stdin
  #         trivy image jndamito/joshrepo:arctiqgame > trivyimage.txt
          
  #     - name: Check Trivy scan result
  #       run: |
  #         SCAN_RESULT=$(trivy image jndamito/joshrepo:arctiqgame)
  #         TRIVY_EXIT_CODE=$?
  #         if [ $TRIVY_EXIT_CODE -eq 0 ]; then
  #         echo "Trivy scan completed successfully."
  #         else
  #           if echo "$SCAN_RESULT" | grep -iqE 'CRITICAL|HIGH'; then
  #           echo "Trivy scan failed with critical or high vulnerabilities."
  #           exit 1
  #           else
  #           echo "Trivy scan passed with medium, low, or unknown vulnerabilities."
  #           fi
          

  # deploy:
  #  needs: [sonar, docker-push, Image-scan]   
  #  runs-on: [Linux]
  #  steps:
  #     - name: Pull Docker image
  #       run: |
  #         docker pull ${{ secrets.JFROG_URL }}/${{ secrets.DOCKER_REPO }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

  #     - name: Image scan
  #       run: trivy image jndamito/joshrepo:arctiqgame > trivyimagedeploy.txt  
  
  #     #- name: Deploy to container
  #       #run: docker run -d --name game -p 3000:3000 jndamito/joshrepo:arctiqgame

  #     - name: Update kubeconfig
  #       run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

  #     - name: Deploy to kubernetes
  #       run: kubectl apply -f deployment.yml

  #     - name: Echo Load Balancer
  #       run: |
  #         kubectl get svc | grep amazon | awk '{print $4}' | cat > arctiq.txt
  #         cat arctiq.txt
  #
# Adding Permission Settings is required
# The attribute id-token: write must be included in the GitHub Actions workflows Permission section. Learn more


