
name: Jira Integration

on:
  workflow_dispatch:

jobs:
  Testing-integration:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      uses: ./
      with:
        from: commits

    - name: Transition issue
      uses: atlassian/gajira-login@v3
      with:
        issue: ${{ steps.create.outputs.issue }}
        transition: "In Progress"

    - name: Comment on issue
      uses: atlassian/gajira-login@v3
      with:
       issue: INC-2
       comment: "${{ github.event.pusher.name }} pushed to repository: ${{ github.event.repository.full_name }}"

